In [1]:
# packages for processing of geospitial data
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [3]:
csvpath = r"C:\Users\USER\Documents\GitHub\collection\dem_extracter\test_data\lichi_example.csv"
lichi_df = pd.read_csv(csvpath)

geo_df = lichi_df.iloc[:,0:3] 
# To select the latitude, longitude, and altitude(m) columns from lichi_df and store them in geo_df
geo_df = geo_df.rename(columns={"latitude": "lat", "longitude": "lon", "altitude(m)": "alt"})
geo_df

          lat         lon  alt
0   24.965710  121.916089   40
1   24.965824  121.916088   40
2   24.966280  121.916084   40
3   24.966394  121.916083   40
4   24.966510  121.916277   40
..        ...         ...  ...
83  24.967563  121.919965   40
84  24.967450  121.920160   40
85  24.967336  121.920161   40
86  24.966994  121.920164   40
87  24.966880  121.920165   40

[88 rows x 3 columns]

In [6]:
geometry = [Point(xy) for xy in zip(geo_df["lon"], geo_df["lat"])] # 表示方式與3826相反
pt = gpd.GeoDataFrame(geo_df, geometry=geometry) # create geodataframe
pt.set_crs(epsg=4326, inplace=True)
pt_3826 = pt.to_crs(epsg=3826) # convert to epsg 3826

pt_3826_x = [point.x for point in pt_3826['geometry']]
pt_3826_y = [point.y for point in pt_3826['geometry']]
print(pt_3826_x)
print(pt_3826_y)

[342498.2300258083, 342498.04391602235, 342497.29946863046, 342497.1133548208, 342516.5738260029, 342516.7599406475, 342517.8766117315, 342518.0627207823, 342537.89541702066, 342537.7093087026, 342536.03429824463, 342535.8481819825, 342555.30865445075, 342555.4947715484, 342557.72811441537, 342557.91422111256, 342577.74691893545, 342577.5608129716, 342574.7691279807, 342574.5830092623, 342594.04348311806, 342594.2296025699, 342597.39351268933, 342597.579617917, 342617.41231805715, 342617.22621356836, 342613.5039579299, 342613.31783685664, 342632.7783119959, 342632.96443390584, 342637.05891570396, 342637.24501935847, 342657.0777218209, 342656.89161900344, 342652.2387881961, 342652.0526645636, 342671.51314108516, 342671.69926545466, 342676.72432346165, 342676.9104255421, 342696.7431304242, 342696.55702908104, 342691.1597438742, 342690.97361856716, 342710.24797038187, 342710.4340972097, 342716.3897359618, 342716.5758364673, 342736.40854376904, 342736.222443901, 342729.89457691286, 342729.70844924694, 342748.9827999797, 342749.16892916954, 342755.8690532828, 342756.05515309895, 342775.1434624251, 342774.9573602044, 342768.8155394895, 342768.6294102498, 342788.6482802713, 342788.8344079909, 342794.0456617089, 342794.2317663373, 342813.50617118337, 342813.3200648328, 342808.6671492052, 342808.4810222173, 342828.31376543525, 342828.4998915859, 342832.4083580092, 342832.5944666658, 342851.68275682954, 342851.49664576334, 342848.51875976747, 342848.3326351355, 342868.16537985136, 342868.351503751, 342870.5849280927, 342870.7710415666, 342889.859320977, 342889.67320499197, 342888.3703711779, 342888.18424890056, 342908.0169952161, 342908.2031167579, 342908.7614765639, 342908.9475949603]
[2762291.6802206156, 2762304.310168086, 2762354.82995782, 2762367.4599052067, 2762380.379364838, 2762367.7494162265, 2762291.9697242035, 2762279.3397754813, 2762266.9993278887, 2762279.629277873, 2762393.2988269557, 2762405.9287767736, 2762418.8482426144, 2762406.218291582, 2762254.658877858, 2762242.028926601, 2762229.6884728596, 2762242.3184253685, 2762431.767710963, 2762444.397663202, 2762457.317135266, 2762444.6871818, 2762229.977970429, 2762217.3480166676, 2762205.007558027, 2762217.6375130527, 2762470.2366098273, 2762482.8665644773, 2762495.786042765, 2762483.156086878, 2762205.2970532137, 2762192.6670969347, 2762180.326633393, 2762192.9565909253, 2762508.7055235417, 2762521.3354806243, 2762534.254965117, 2762521.6250068187, 2762180.6161261853, 2762167.9861674006, 2762155.645698967, 2762168.275658994, 2762534.5444925968, 2762547.1744521107, 2762572.7239023387, 2762560.0939416173, 2762155.9351893635, 2762143.305228071, 2762130.9647547347, 2762143.594717268, 2762573.0134336036, 2762585.6433955515, 2762611.192854413, 2762598.5628912677, 2762143.8842065125, 2762131.2542427327, 2762169.433625788, 2762182.063590758, 2762598.8524250844, 2762611.4823894757, 2762586.5119933183, 2762573.882027655, 2762220.242982301, 2762207.6130161537, 2762233.1624464737, 2762245.79241383, 2762561.5415921756, 2762574.1715590945, 2762561.831122411, 2762549.201154249, 2762283.9718188066, 2762271.341850271, 2762309.521261382, 2762322.1512311073, 2762524.2307444373, 2762536.860713872, 2762524.5202710456, 2762511.890300345, 2762360.330650711, 2762347.7006797967, 2762385.880105527, 2762398.5100776306, 2762486.9198818514, 2762499.5498538148, 2762487.2094048336, 2762474.579431615, 2762436.6895118575, 2762424.059538574]

In [ ]:



# test data
flypath = pd.read_csv("C:/Users/USER/Desktop/飛行任務/dont_curved.csv") # test data
# flypath.head()
geometry = [Point(xy) for xy in zip(flypath["longitude"], flypath["latitude"])] # longitude(x), latitude(y) Column name in Litchi csv format
crs = 'EPSG:4326' # default coord system of geometry in Litchi csv
fp = gpd.GeoDataFrame(flypath, geometry=geometry, crs=crs) # create geodataframe
#fp.head() # GeoDataFrame
fp_3826 = fp.to_crs('EPSG:3826')
 # transform crs using geopandas method, MPP.PY I/O

# extract geometry by list, x and y
fp_3826_x = [point.x for point in fp_3826['geometry']]
fp_3826_y = [point.y for point in fp_3826['geometry']]
print(fp_3826_x)
print(fp_3826_y)

'''
class LitchiWaypoint:
    def __init__(x_coords,y_coords,altitude):
        x_coords = fp_3826_x
        y_coords = fp_3826_y
        altitude = fp_3826["altitude(m)"]
'''